# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmation', to='orders.Order')),
                ('orderitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_confirmation', to='orders.OrderItem')),
            ],
        ),
    ]
