# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='address',
            field=models.CharField(default='t', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
